# -*- coding: utf-8 -*-
"""Neural Network Model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZckXyWno1i0AR9KL0NSRTaGYyFEcOGSc

# Importing the libraries

---
"""

import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
import matplotlib.pyplot as plt

tf.__version__

"""# Read dataset and select the features , output

---


"""

dataset = pd.read_excel('Folds5x2_pp.xlsx')
cols = dataset.shape[1]
X = dataset.iloc[: , 0:cols-1]
y = dataset.iloc[: ,cols-1:cols]

print(X.head())
print(y.head())

"""# spliting the data to 0.8 training , 0.2 testing

---


"""

x_train , x_test , y_train , y_test =train_test_split(X , y , test_size=0.3 , random_state=44 , shuffle=True)

print(x_train.shape)

"""# building the neural network

---


"""

ANN = Sequential([
      Dense(units=6 , activation='relu'),
      Dense(units=6 , activation ='relu'),
      Dense(units=1)
])

"""# compiling the neural network (Errors)

---


"""

ANN.compile(optimizer='adam' , loss='mean_squared_error')

"""# fitting the neural network (training the model)

---


"""

ANN.fit(x_train , y_train ,batch_size=32, epochs=100)

"""# compare the output of my model with the real output

---


"""

y_pred = ANN.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.values.reshape(len(y_test),1)),1))

plt.plot(y_pred[0:100])